import './globals.css'
import { Inter } from 'next/font/google'
import Menu from '@/components/Menu'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  const elemens = ["Elemento 1", "Elemento 2", "Elemento 3"]
  return (
    <html lang="en">
      <body className={inter.className}>
        <Menu elementos = {elemens}/>
        {children}
      </body>
    </html>
  )
}
